import type {
  Product,
  ProductCategory,
  Review,
  Order,
  SellerProfile,
  DashboardStats,
  Dispute,
} from '../types';

export const categories: ProductCategory[] = [
  { id: 'cat-1', name: 'Handicrafts', slug: 'handicrafts', icon: 'Palette' },
  { id: 'cat-2', name: 'Clothing', slug: 'clothing', icon: 'Shirt' },
  { id: 'cat-3', name: 'Electronics', slug: 'electronics', icon: 'Smartphone' },
  { id: 'cat-4', name: 'Home & Garden', slug: 'home-garden', icon: 'Home' },
  { id: 'cat-5', name: 'Food & Spices', slug: 'food-spices', icon: 'Leaf' },
  { id: 'cat-6', name: 'Jewelry', slug: 'jewelry', icon: 'Gem' },
  { id: 'cat-7', name: 'Books & Stationery', slug: 'books', icon: 'BookOpen' },
  { id: 'cat-8', name: 'Sports & Outdoors', slug: 'sports', icon: 'Trophy' },
];

const sellerProfiles: Pick<SellerProfile, 'id' | 'storeName' | 'rating' | 'avatar'>[] = [
  { id: 'seller-1', storeName: 'Lahore Crafts Co.', rating: 4.8, avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=LC' },
  { id: 'seller-2', storeName: 'Karachi Threads', rating: 4.5, avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=KT' },
  { id: 'seller-3', storeName: 'Islamabad Tech Hub', rating: 4.7, avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=IT' },
  { id: 'seller-4', storeName: 'Peshawar Spice Market', rating: 4.9, avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=PS' },
  { id: 'seller-5', storeName: 'Multan Pottery Works', rating: 4.6, avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MP' },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    title: 'Hand-Embroidered Sindhi Ajrak Shawl',
    description: 'Authentic hand-embroidered Sindhi Ajrak shawl made with traditional block printing techniques. Each piece is unique and crafted by skilled artisans from Sindh province. Perfect for cultural events and everyday elegance.',
    price: 2500,
    originalPrice: 3500,
    images: ['https://placehold.co/600x600/16a34a/ffffff?text=Ajrak+Shawl'],
    category: categories[1],
    seller: sellerProfiles[0],
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    tags: ['handmade', 'traditional', 'sindhi', 'ajrak'],
    createdAt: '2026-03-15T10:00:00Z',
    isFeatured: true,
  },
  {
    id: 'prod-2',
    title: 'Blue Pottery Vase - Multan Heritage',
    description: 'Exquisite blue pottery vase handcrafted in Multan using centuries-old techniques. This decorative piece features intricate floral patterns in cobalt blue and turquoise. A perfect addition to any home.',
    price: 4200,
    originalPrice: 5000,
    images: ['https://placehold.co/600x600/9333ea/ffffff?text=Blue+Pottery'],
    category: categories[0],
    seller: sellerProfiles[4],
    rating: 4.9,
    reviewCount: 89,
    stock: 8,
    tags: ['pottery', 'handmade', 'multan', 'heritage'],
    createdAt: '2026-03-10T08:00:00Z',
    isFeatured: true,
  },
  {
    id: 'prod-3',
    title: 'Wireless Bluetooth Earbuds Pro',
    description: 'High-quality wireless earbuds with active noise cancellation, 30-hour battery life, and IPX5 water resistance. Includes wireless charging case and premium ear tips for comfort.',
    price: 3800,
    originalPrice: 5500,
    images: ['https://placehold.co/600x600/1e40af/ffffff?text=Earbuds+Pro'],
    category: categories[2],
    seller: sellerProfiles[2],
    rating: 4.5,
    reviewCount: 312,
    stock: 50,
    tags: ['electronics', 'earbuds', 'wireless', 'bluetooth'],
    createdAt: '2026-03-20T14:00:00Z',
    isFeatured: true,
  },
  {
    id: 'prod-4',
    title: 'Premium Kashmiri Saffron (10g)',
    description: 'Grade A Kashmiri saffron sourced directly from farmers. Known for its rich aroma, vibrant color, and superior flavor. Lab-tested for purity and packaged in an airtight container.',
    price: 1800,
    originalPrice: 2200,
    images: ['https://placehold.co/600x600/dc2626/ffffff?text=Saffron'],
    category: categories[4],
    seller: sellerProfiles[3],
    rating: 4.9,
    reviewCount: 67,
    stock: 30,
    tags: ['saffron', 'spices', 'kashmiri', 'organic'],
    createdAt: '2026-03-18T09:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-5',
    title: 'Handwoven Swati Shawl',
    description: 'Luxurious handwoven Swati shawl from the scenic valleys of Swat. Made with finest quality wool featuring traditional geometric patterns. Perfect for winters and special occasions.',
    price: 6500,
    originalPrice: 8000,
    images: ['https://placehold.co/600x600/7e22ce/ffffff?text=Swati+Shawl'],
    category: categories[1],
    seller: sellerProfiles[0],
    rating: 4.7,
    reviewCount: 45,
    stock: 12,
    tags: ['shawl', 'handwoven', 'swati', 'wool'],
    createdAt: '2026-03-22T11:00:00Z',
    isFeatured: true,
  },
  {
    id: 'prod-6',
    title: 'Traditional Peshawari Chappal',
    description: 'Authentic Peshawari chappal handmade by skilled cobblers. Premium leather construction with intricate stitching. Available in multiple sizes. A symbol of Pashtun heritage.',
    price: 2200,
    originalPrice: 2800,
    images: ['https://placehold.co/600x600/92400e/ffffff?text=Chappal'],
    category: categories[1],
    seller: sellerProfiles[3],
    rating: 4.6,
    reviewCount: 198,
    stock: 25,
    tags: ['footwear', 'leather', 'peshawari', 'handmade'],
    createdAt: '2026-03-12T16:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-7',
    title: 'Smart Home LED Bulb Set (4 Pack)',
    description: 'WiFi-enabled smart LED bulbs compatible with Alexa and Google Home. 16 million colors, dimmable, and energy efficient. Set schedules and control from anywhere via app.',
    price: 2400,
    originalPrice: 3200,
    images: ['https://placehold.co/600x600/ea580c/ffffff?text=Smart+Bulbs'],
    category: categories[3],
    seller: sellerProfiles[2],
    rating: 4.3,
    reviewCount: 156,
    stock: 40,
    tags: ['smart-home', 'led', 'wifi', 'automation'],
    createdAt: '2026-03-25T13:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-8',
    title: 'Handcrafted Silver Jhumka Earrings',
    description: 'Sterling silver jhumka earrings handcrafted by artisans from Hyderabad. Features traditional bell-shaped design with delicate filigree work. Lightweight and hypoallergenic.',
    price: 3200,
    originalPrice: 4000,
    images: ['https://placehold.co/600x600/be185d/ffffff?text=Jhumka'],
    category: categories[5],
    seller: sellerProfiles[0],
    rating: 4.8,
    reviewCount: 73,
    stock: 18,
    tags: ['jewelry', 'silver', 'jhumka', 'handcrafted'],
    createdAt: '2026-03-28T10:00:00Z',
    isFeatured: true,
  },
  {
    id: 'prod-9',
    title: 'Urdu Calligraphy Art Print Set',
    description: 'Set of 3 premium Urdu calligraphy art prints on museum-quality paper. Features famous poetry verses by Iqbal and Ghalib. Unframed, perfect for home or office decor.',
    price: 1500,
    originalPrice: 2000,
    images: ['https://placehold.co/600x600/4338ca/ffffff?text=Calligraphy'],
    category: categories[0],
    seller: sellerProfiles[4],
    rating: 4.4,
    reviewCount: 34,
    stock: 50,
    tags: ['art', 'calligraphy', 'urdu', 'poetry'],
    createdAt: '2026-03-30T09:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-10',
    title: 'Cricket Leather Ball - Test Grade',
    description: 'Premium hand-stitched cricket leather ball meeting international test match standards. 4-piece construction with cork core. Made in Sialkot, the sporting goods capital of Pakistan.',
    price: 1200,
    originalPrice: 1600,
    images: ['https://placehold.co/600x600/dc2626/ffffff?text=Cricket+Ball'],
    category: categories[7],
    seller: sellerProfiles[3],
    rating: 4.7,
    reviewCount: 210,
    stock: 100,
    tags: ['cricket', 'sports', 'leather', 'sialkot'],
    createdAt: '2026-03-08T15:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-11',
    title: 'Portable Power Bank 20000mAh',
    description: 'High-capacity portable power bank with fast charging support. Features dual USB-A and USB-C ports. Compact design with LED battery indicator. Charge 3 devices simultaneously.',
    price: 2800,
    originalPrice: 3600,
    images: ['https://placehold.co/600x600/0369a1/ffffff?text=Power+Bank'],
    category: categories[2],
    seller: sellerProfiles[2],
    rating: 4.4,
    reviewCount: 178,
    stock: 35,
    tags: ['electronics', 'power-bank', 'charging', 'portable'],
    createdAt: '2026-03-14T12:00:00Z',
    isFeatured: false,
  },
  {
    id: 'prod-12',
    title: 'Truck Art Decorative Plate',
    description: 'Vibrant truck art style decorative plate hand-painted by Karachi artisans. Features traditional jingle truck motifs with floral and geometric patterns. Wall-mountable with display stand included.',
    price: 1800,
    originalPrice: 2500,
    images: ['https://placehold.co/600x600/b91c1c/ffffff?text=Truck+Art'],
    category: categories[0],
    seller: sellerProfiles[1],
    rating: 4.6,
    reviewCount: 52,
    stock: 20,
    tags: ['truck-art', 'decorative', 'handpainted', 'karachi'],
    createdAt: '2026-03-26T08:00:00Z',
    isFeatured: true,
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'user-1',
    userName: 'Aisha Khan',
    userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=AK',
    rating: 5,
    comment: 'Absolutely beautiful! The craftsmanship is exceptional. Received exactly as shown in the pictures.',
    isVerifiedPurchase: true,
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userId: 'user-2',
    userName: 'Omar Farooq',
    userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=OF',
    rating: 4,
    comment: 'Great quality shawl. The colors are vibrant and the fabric is soft. Delivery was on time.',
    isVerifiedPurchase: true,
    createdAt: '2026-03-22T14:00:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    userId: 'user-3',
    userName: 'Fatima Noor',
    userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=FN',
    rating: 5,
    comment: 'Best earbuds in this price range! Noise cancellation works great and battery life is impressive.',
    isVerifiedPurchase: true,
    createdAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-2',
    userId: 'user-4',
    userName: 'Hassan Ali',
    userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=HA',
    rating: 5,
    comment: 'Stunning piece of art! It looks even better in person. The blue color is mesmerizing.',
    isVerifiedPurchase: true,
    createdAt: '2026-03-19T11:00:00Z',
  },
];

export const mockSellerProfile: SellerProfile = {
  id: 'seller-1',
  name: 'Bilal Ahmed',
  email: 'bilal@lahorecrafts.pk',
  role: 'seller',
  avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=BA',
  phone: '+92-321-1234567',
  joinedAt: '2025-06-15T00:00:00Z',
  isVerified: true,
  storeName: 'Lahore Crafts Co.',
  storeDescription: 'Premium handcrafted goods from the heart of Punjab',
  cnicVerified: true,
  ntnNumber: '1234567-8',
  totalSales: 1247,
  rating: 4.8,
  reviewCount: 324,
};

export const dashboardStats: DashboardStats = {
  totalRevenue: 2450000,
  totalOrders: 1247,
  totalProducts: 48,
  averageRating: 4.8,
  revenueChange: 12.5,
  ordersChange: 8.3,
  monthlyRevenue: [
    { month: 'Oct', revenue: 180000 },
    { month: 'Nov', revenue: 220000 },
    { month: 'Dec', revenue: 350000 },
    { month: 'Jan', revenue: 280000 },
    { month: 'Feb', revenue: 310000 },
    { month: 'Mar', revenue: 420000 },
  ],
};

export const mockOrders: Order[] = [
  {
    id: 'ORD-2026-001',
    buyerId: 'user-1',
    sellerId: 'seller-1',
    items: [{ product: products[0], quantity: 2 }],
    totalAmount: 5000,
    status: 'delivered',
    paymentMethod: 'jazzcash',
    shippingAddress: {
      fullName: 'Aisha Khan',
      phone: '+92-300-1234567',
      addressLine1: 'House 45, Street 12',
      addressLine2: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54000',
    },
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
    trackingNumber: 'TCS-12345678',
    estimatedDelivery: '2026-03-20T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-03-15T10:00:00Z', note: 'Order placed' },
      { status: 'confirmed', timestamp: '2026-03-15T12:30:00Z', note: 'Payment verified via JazzCash' },
      { status: 'processing', timestamp: '2026-03-16T09:00:00Z', note: 'Seller is preparing your order' },
      { status: 'shipped', timestamp: '2026-03-17T14:00:00Z', note: 'Dispatched via TCS — TCS-12345678' },
      { status: 'delivered', timestamp: '2026-03-20T10:00:00Z', note: 'Delivered to recipient' },
    ],
  },
  {
    id: 'ORD-2026-002',
    buyerId: 'user-1',
    sellerId: 'seller-3',
    items: [{ product: products[2], quantity: 1 }],
    totalAmount: 3800,
    status: 'shipped',
    paymentMethod: 'cod',
    shippingAddress: {
      fullName: 'Aisha Khan',
      phone: '+92-300-1234567',
      addressLine1: 'House 45, Street 12',
      addressLine2: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54000',
    },
    createdAt: '2026-03-28T14:00:00Z',
    updatedAt: '2026-03-30T09:00:00Z',
    trackingNumber: 'LEP-87654321',
    estimatedDelivery: '2026-04-03T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-03-28T14:00:00Z', note: 'Order placed (COD)' },
      { status: 'confirmed', timestamp: '2026-03-28T16:00:00Z', note: 'Confirmed by seller' },
      { status: 'processing', timestamp: '2026-03-29T10:00:00Z', note: 'Packaging your order' },
      { status: 'shipped', timestamp: '2026-03-30T09:00:00Z', note: 'Dispatched via Leopards — LEP-87654321' },
    ],
  },
  {
    id: 'ORD-2026-003',
    buyerId: 'user-1',
    sellerId: 'seller-5',
    items: [{ product: products[1], quantity: 1 }, { product: products[3], quantity: 2 }],
    totalAmount: 7800,
    status: 'processing',
    paymentMethod: 'easypaisa',
    shippingAddress: {
      fullName: 'Aisha Khan',
      phone: '+92-300-1234567',
      addressLine1: 'House 45, Street 12',
      addressLine2: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54000',
    },
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-04-02T11:00:00Z',
    trackingNumber: '',
    estimatedDelivery: '2026-04-07T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-04-01T08:00:00Z', note: 'Order placed' },
      { status: 'confirmed', timestamp: '2026-04-01T10:00:00Z', note: 'Payment verified via EasyPaisa' },
      { status: 'processing', timestamp: '2026-04-02T11:00:00Z', note: 'Seller is preparing your order' },
    ],
  },
  {
    id: 'ORD-2026-004',
    buyerId: 'user-1',
    sellerId: 'seller-1',
    items: [{ product: products[7], quantity: 1 }],
    totalAmount: 3200,
    status: 'confirmed',
    paymentMethod: 'card',
    shippingAddress: {
      fullName: 'Aisha Khan',
      phone: '+92-300-1234567',
      addressLine1: 'House 45, Street 12',
      addressLine2: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54000',
    },
    createdAt: '2026-04-02T16:00:00Z',
    updatedAt: '2026-04-02T18:00:00Z',
    trackingNumber: '',
    estimatedDelivery: '2026-04-08T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-04-02T16:00:00Z', note: 'Order placed' },
      { status: 'confirmed', timestamp: '2026-04-02T18:00:00Z', note: 'Payment confirmed via card' },
    ],
  },
  {
    id: 'ORD-2026-005',
    buyerId: 'user-1',
    sellerId: 'seller-4',
    items: [{ product: products[5], quantity: 2 }],
    totalAmount: 4400,
    status: 'cancelled',
    paymentMethod: 'jazzcash',
    shippingAddress: {
      fullName: 'Aisha Khan',
      phone: '+92-300-1234567',
      addressLine1: 'House 45, Street 12',
      addressLine2: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54000',
    },
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-03-11T09:00:00Z',
    trackingNumber: '',
    estimatedDelivery: '',
    statusHistory: [
      { status: 'pending', timestamp: '2026-03-10T11:00:00Z', note: 'Order placed' },
      { status: 'cancelled', timestamp: '2026-03-11T09:00:00Z', note: 'Cancelled by buyer — changed mind' },
    ],
  },
  {
    id: 'ORD-2026-006',
    buyerId: 'user-2',
    sellerId: 'seller-1',
    items: [{ product: products[4], quantity: 1 }],
    totalAmount: 6500,
    status: 'pending',
    paymentMethod: 'bank_transfer',
    shippingAddress: {
      fullName: 'Omar Farooq',
      phone: '+92-333-9876543',
      addressLine1: 'Flat 8, Block C',
      addressLine2: 'Clifton',
      city: 'Karachi',
      province: 'Sindh',
      postalCode: '75600',
    },
    createdAt: '2026-04-03T07:00:00Z',
    updatedAt: '2026-04-03T07:00:00Z',
    trackingNumber: '',
    estimatedDelivery: '2026-04-09T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-04-03T07:00:00Z', note: 'Order placed — awaiting bank transfer confirmation' },
    ],
  },
  {
    id: 'ORD-2026-007',
    buyerId: 'user-3',
    sellerId: 'seller-1',
    items: [{ product: products[8], quantity: 3 }],
    totalAmount: 4500,
    status: 'shipped',
    paymentMethod: 'easypaisa',
    shippingAddress: {
      fullName: 'Fatima Noor',
      phone: '+92-345-5678901',
      addressLine1: 'House 12, F-7/2',
      addressLine2: '',
      city: 'Islamabad',
      province: 'ICT',
      postalCode: '44000',
    },
    createdAt: '2026-03-29T13:00:00Z',
    updatedAt: '2026-04-01T16:00:00Z',
    trackingNumber: 'TCS-99887766',
    estimatedDelivery: '2026-04-04T00:00:00Z',
    statusHistory: [
      { status: 'pending', timestamp: '2026-03-29T13:00:00Z', note: 'Order placed' },
      { status: 'confirmed', timestamp: '2026-03-29T15:00:00Z', note: 'Payment verified' },
      { status: 'processing', timestamp: '2026-03-30T10:00:00Z', note: 'Preparing calligraphy prints' },
      { status: 'shipped', timestamp: '2026-04-01T16:00:00Z', note: 'Dispatched via TCS — TCS-99887766' },
    ],
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: 'DSP-001',
    orderId: 'ORD-2026-050',
    buyerName: 'Zainab Malik',
    sellerName: 'Quick Electronics',
    reason: 'Product received is different from listing description',
    status: 'open',
    createdAt: '2026-03-29T10:00:00Z',
  },
  {
    id: 'DSP-002',
    orderId: 'ORD-2026-043',
    buyerName: 'Usman Shah',
    sellerName: 'Karachi Threads',
    reason: 'Item not received after 15 days',
    status: 'investigating',
    createdAt: '2026-03-25T14:00:00Z',
  },
  {
    id: 'DSP-003',
    orderId: 'ORD-2026-038',
    buyerName: 'Hira Aslam',
    sellerName: 'Peshawar Spice Market',
    reason: 'Damaged packaging, spice container was broken',
    status: 'resolved',
    createdAt: '2026-03-20T09:00:00Z',
  },
];
